packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - prisma
  - puppeteer
  - sharp
  - unrs-resolver
