import type { Metadata } from "next";
import "@/app/globals.css";
import { cookies } from "next/headers";
import GlobalLayout, { roboto } from "@/components/GlobalLayout";
import { Layout } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DealerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const LayoutProps = {
    userType: (await cookies()).get("user_type")?.value,
  };
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <GlobalLayout>
          <Layout {...LayoutProps}>{children}</Layout>
        </GlobalLayout>
      </body>
    </html>
  );
}
