import type { Metadata } from "next";
import "@/app/globals.css";
import GlobalLayout, { roboto } from "@/components/GlobalLayout";
import { Layout } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DealerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <GlobalLayout>
          <Layout>{children}</Layout>
        </GlobalLayout>
      </body>
    </html>
  );
}
