import type { Metadata } from "next";
import "@/app/globals.css";
import GlobalLayout, { roboto } from "@/components/GlobalLayout";
import { Layout } from "@/components/Sidebar";
import theme from "@/theme";
import Footer from "./components/Footer";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <GlobalLayout>
          <Layout>
            <Header theme={theme} />
            {children}
            <Footer theme={theme} />
          </Layout>
        </GlobalLayout>
      </body>
    </html>
  );
}
