name: Test Docker Build

# on:
#   push:
#     branches:
#       - master
#       - main
#   pull_request:
#     branches:
#       - master
#       - main
on:
  push:
  pull_request:
jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t crm-test .